export const settingsActions = {
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  TOGGLE_ARABIC: "TOGGLE_ARABIC",
  TOGGLE_TRANSLATION: "TOGGLE_TRANSLATION",
  TOGGLE_TRANSLITERATION: "TOGGLE_TRANSLITERATION",
  TOGGLE_REFFERENCE: "TOGGLE_REFFERENCE",
  CHANGE_TRANSLATION_FONT_SIZE: "CHANGE_TRANSLATION_FONT_SIZE",
  CHANGE_ARABIC_FONT_SIZE: "CHANGE_ARABIC_FONT_SIZE",
  CHANGE_ARABIC_SCRIPT: "CHANGE_ARABIC_SCRIPT",
  CHANGE_ARABIC_FONT: "CHANGE_ARABIC_FONT",
};
